### ISSUE TITLE
Wrong dependency on npm

### ISSUE THREAD

**Issue by Crawleyprint** [inuitcss/starter-kit#4]
@anselmh @csswizardry 

error: `Error: version not found: 0.2.3 : inuit-mixins/0.2.3`. 

npmjs.org reports 0.2.2 as most recent version of `inuit-mixins`, and package.json from `inuit-starter-kit` asks for 0.2.3

**Comment by anselmh** [comment]
Sorry about that. I fixed it and published `0.2.3` to npm, too in https://github.com/inuitcss/tools.mixins/commit/a19c4f4daad88127ee379133d78750885d29d1d2. It’s now on npm: https://www.npmjs.com/package/inuit-mixins
