### ISSUE TITLE
starter-kit with everything

### ISSUE THREAD

**Issue by benknight** [inuitcss/starter-kit#6]
I use most of the framework so I'd rather opt-out of what I don't want instead of opt-in to what I do.  It would be cool to have a version of the starter kit that installed all dependencies.  Thoughts?

**Comment by Crawleyprint** [comment]
I think that defeats the purpose of starter-kit which should be bare minimum to get you going. Bootstrap uses similar approach to what you've described and yet, very little people opt-out of anything and instead use all of it.

**Comment by csshugs** [comment]
@Crawleyprint 

> very little people opt-out of anything and instead use all of it

agree

@benknight You could still provide a "all-of-inuit"-repo youself. Basically it's just one bower.json/package.json file listing all inuicss components.

**Comment by soundyogi** [comment]
I found it hard to get an Overview of all the modules aswell so I have thrown this together:

https://github.com/soundyogi/inuit-full-kit

**Comment by anselmh** [comment]
Hey, I’m going to close this issue for now. We are currently evaluating ideas for an upcoming next major version of inuitcss but it’s unlikely that we fix this in the current version.
We do want to improve here so this one is going to be addressed.
Thanks for the contribution and idea!
